export const movies = [ { 
title: "Toy Story", 
genre: "Comédia", 
        ageRating: livre,
synopsis: "O aniversário de Andy está chegando e os brinquedos estão nervosos. Afinal de contas, eles temem que um novo brinquedo possa substituí-los. Liderados por Woody, um caubói que é também o brinquedo predileto de Andy, eles montam uma escuta que lhes permite saber dos presentes ganhos. Entre eles está Buzz Lightyear, o boneco de um patrulheiro espacial, que logo passa a receber mais atenção do garoto. Isto aos poucos gera ciúmes em Woody, que tenta fazer com que ele caia atrás da cama. Só que o plano dá errado e Buzz cai pela janela. É o início da aventura de Woody, que precisa resgatar Buzz também para limpar sua barra com os outros brinquedos.”
trailer: “https://m.youtube.com/watch?v=_8vw4UikKhg&pp=ygUndG95IHN0b3J5IHVtIG11bmRvIGRlIGF2ZW50dXJhcyB0cmFpbGVy “
}, 
{ 
title: "Até que a sorte nos separe", 
genre: "Comédia", 
        ageRating: 10, 
synopsis: "Tino (Leandro Hassum) é um pai de família comum que vê sua vida virar de ponta a cabeça após ganhar na loteria. Levando uma vida de ostentação ao lado da mulher, Jane (Danielle Winits), ele gasta todo o dinheiro em 15 anos. Ao se ver quebrado, Tino aceita a ajuda do vizinho Amauri (Kiko Mascarenhas), um consultor de finanças super burocrático e que por sinal vive seu próprio drama ao enfrentar uma crise no casamento com Laura (Rita Elmôr). Tentando evitar que Jane descubra a nova situação financeira, afinal ela está grávida do terceiro filho não pode passar por fortes emoções, Tino se envolve em várias confusões para fingir que tudo continua bem. Para isso, conta com ajuda do melhor amigo, Adelson (Aílton Graça), e dos filhos.", 
trailer: "https://m.youtube.com/watch?v=dAnzuTb-A8k&pp=ygUjYXTDqSBxdWUgYSBzb3J0ZSBub3Mgc2VwYXJlIHRyYWlsZXI%3D “
}, 
{ 
title: "A sogra perfeita", 
genre: "Comédia", 
        ageRating: 12, 
synopsis: "Em A Sogra Perfeita, Neide (Cacau Protásio) é uma mulher de 40 e poucos anos que se separou do marido há pouco tempo e sonha em aproveitar a vida de solteira. Dona de um badalado salão de beleza do subúrbio de São Paulo, ela colocou seus dois filhos na faculdade, mas o mais novo, Fábio Junior (Luis Navarro), não dá nem sinal de sair de casa. Para enfim alcançar a tão sonhada liberdade, ela decide treinar uma funcionária para ser a esposa perfeita para seu filho.", 
trailer: "https://m.youtube.com/watch?v=wqRxoOh7osk&pp=ygUYYSBzb2dyYSBwZXJmZWl0YSB0cmFpbGVy “
}, 
{ 
title: " O pai, o", 
genre: " Comédia", 
        ageRating: 14, 
synopsis: "A história, que levanta diversas críticas sociais, mostra a vida de Roque (Lázaro Ramos), um cantor que está sempre atento para defender sua comunidade e toda a cultura baiana. Ele acaba entrando em conflito com Queixão (Mathues Nachtergaele), que se enfrentam em cômicas situações. Queixão é um homem racista e sem escrúpulos que sobrevive à custa de tráfico de drogas e outros crimes. Roque, que sonha em ser um grande e famoso cantor, tem a ajuda de seus amigos, que o dão suporte, como Neuzão (Tânia Toko), dona de um bar onde Roque se apresenta e palco de diversas situações divertidas da série.", 
trailer: "https://m.youtube.com/watch?v=0VK2LM0R7Mk&pp=ygURw7MgcGFpIMOzIHRyYWlsZXI%3D “
}, 
{ 
title: "O homem que desafiou o diabo", 
genre: "Comédia", 
        ageRating: 16, 
synopsis: "Zé Araújo (Marcos Palmeira) é um homem boêmio, que gosta de frequentar cabarés e ouvir cantadores de viola. Após tirar a virgindade de uma turca, ele é obrigado pelo pai dela a se casar. Durante anos Zé passa por seguidas humilhações, provocadas por sua esposa. Um dia, ao ouvir uma piada sobre sua situação, ele se revolta, destrói o armazém do sogro e ainda dá uma surra na esposa. Ao terminar ele monta em seu cavalo e parte sem destino, decidido a ter uma vida de aventuras. A partir deste dia Zé Araújo passa a ser conhecido como Ojuara, enfrentando inimigos e vivendo situações inusitadas.", 
trailer: "https://m.youtube.com/watch?v=5r0FC3Eki9k&pp=ygUlbyBob21lbSBxdWUgZGVzYWZpb3UgbyBkaWFibyB0cmFpbGVyIA%3D%3D “
}, 
{ 
title: "A procura da felicidade", 
genre: "Drama", 
        ageRating: Livre, 
synopsis: "Em À Procura da Felicidade, Chris Gardner (Will Smith) é um pai de família que enfrenta sérios problemas financeiros. Apesar de todas as tentativas em manter a família unida, Linda (Thandie Newton), sua esposa, decide partir. Chris agora é pai solteiro e precisa cuidar de Christopher (Jaden Smith), seu filho de apenas 5 anos. Ele tenta usar sua habilidade como vendedor para conseguir um emprego melhor, que lhe dê um salário mais digno. Chris consegue uma vaga de estagiário numa importante corretora de ações, mas não recebe salário pelos serviços prestados. Sua esperança é que, ao fim do programa de estágio, ele seja contratado e assim tenha um futuro promissor na empresa. Porém seus problemas financeiros não podem esperar que isto aconteça, o que faz com que sejam despejados. Chris e Christopher passam a dormir em abrigos, estações de trem, banheiros e onde quer que consigam um refúgio à noite, mantendo a esperança de que dias melhores virão.", 
trailer: "https://m.youtube.com/watch?v=yHgiEADa5M8&pp=ygUfYSBwcm9jdXJhIGRhIGZlbGljaWRhZGUgdHJhaWxlcg%3D%3D “
}, 
{ 
title: "Extraordinário",
genre: "Drama", 
ageRating: 10, 
synopsis: "Auggie Pullman (Jacob Tremblay) é um garoto que nasceu com uma deformação facial, o que fez com que passasse por 27 cirurgias plásticas. Aos 10 anos, ele pela primeira vez frequentará uma escola regular, como qualquer outra criança. Lá, precisa lidar com a sensação constante de ser sempre observado e avaliado por todos à sua volta.", 
trailer: "https://m.youtube.com/watch?v=ASAGdtAJPnU “
}, 
{ 
title: "Central do Brasil", 
genre: "Drama", 
ageRating: 12, 
synopsis: "Em Central do Brasil, Dora (Fernanda Montenegro) trabalha escrevendo cartas para analfabetos na estação Central do Brasil, no centro da cidade do Rio de Janeiro. Ainda que a escrivã não envie todas as cartas que escreve - as cartas que considera inúteis ou fantasiosas demais -, ela decide ajudar um menino (Vinícius de Oliveira), após sua mãe ser atropelada, a tentar encontrar o pai que nunca conheceu, no interior do Nordeste.", 
trailer: "https://m.youtube.com/watch?v=JSWgOhRjJmo&pp=ygUZY2VudHJhbCBkbyBicmFzaWwgdHJhaWxlcg%3D%3D “
}, 
{ 
title: "O livro de Henry", 
genre: "Drama", 
ageRating: 14,
 synopsis: "Henry e Peter são dois irmãos criados pela sua mãe solteira, Susan. Henry, apaixonado pela sua vizinha Christina, escreve um livro de resgate para tirá-la dos maus tratos do pai policial. Quando sua mãe descobre sobre o seu plano, ela decide que eles irão colocar a ideia em prática.", 
trailer: "https://m.youtube.com/watch?v=r2HPvSx1tog “
}, 
{ 
title: "Cidade de Deus", 
genre: "Drama", 
ageRating: 16,
 synopsis: "Dadinho (Douglas Silva) e Buscapé são grandes amigos, que cresceram juntos imersos em um universo de muita violência. Na Cidade de Deus, favela carioca conhecida por ser um dos locais mais violentos do Rio de Janeiro, os caminhos das duas crianças divergem, quando um se esforça para se tornar um fotógrafo e o outro o chefe do tráfico. Buscapé (Alexandre Rodrigues) é um jovem pobre, negro e muito sensível, que vive amedrontado com a possibilidade de se tornar um bandido, e acaba sendo salvo de seu destino por causa de seu talento como fotógrafo, o qual permite que siga carreira na profissão. É através de seu olhar atrás da câmera que Buscapé analisa o dia-a-dia da favela onde vive, enquanto Dadinho, agora Zé Pequeno (Leandro Firmino), se torna o temido chefe do tráfico da região, continuando com o legado de violência que remonta a décadas anteriores - e parece ser infinita. Considerado um dos melhores filmes da história do cinema brasileiro.", 
trailer: "https://m.youtube.com/watch?v=fZJUKixyeXM “
}, 
{ 
title: "Viva - A vida é uma festa", 
genre: "Animação", 
ageRating: Livre,
 synopsis: "Em Viva - A Vida é uma Festa, Miguel é um menino de 12 anos que quer muito ser um músico famoso, mas ele precisa lidar com sua família que desaprova seu sonho. Determinado a virar o jogo, ele acaba desencadeando uma série de eventos ligados a um mistério de 100 anos. A aventura, com inspiração no feriado mexicano do Dia dos Mortos, acaba gerando uma extraordinária reunião familiar.", 
trailer: "https://m.youtube.com/watch?v=Rvr68u6k5sI “
}, 
{ 
title: "Homem aranha no aranhaverso", 
genre: "Animação", 
ageRating: 10, 
synopsis: "Em Homem-Aranha no Aranhaverso, Miles Morales é um jovem negro do Brooklyn que se tornou o Homem-Aranha inspirado no legado de Peter Parker, já falecido. Entretanto, ao visitar o túmulo de seu ídolo em uma noite chuvosa, ele é surpreendido com a presença do próprio Peter, vestindo o traje do herói aracnídeo sob um sobretudo. A surpresa fica ainda maior quando Miles descobre que ele veio de uma dimensão paralela, assim como outras versões do Homem-Aranha", 
trailer: "https://m.youtube.com/watch?v=IrQ3iLUKr0I “
}, 
{ 
title: "Uma história de amor e fúria", 
genre: "Animação", 
ageRating: 12,
 synopsis: "Um homem (Selton Mello) com quase 600 anos de idade acompanha a história do Brasil, enquanto procura a ressurreição de sua amada Janaína (Camila Pitanga). Ele enfrenta as batalhas entre tupinambás e tupiniquins, antes dos portugueses chegarem ao país, e passa pela Balaiada e o movimento de resistência contra a ditadura militar, antes de enfrentar a guerra pela água em 2096.", 
trailer: "https://m.youtube.com/watch?v=V9BHvEHKRaM&pp=ygUmdW1hIGhpc3TDs3JpYSBkZSBhbW9yIGUgZsO6cmlhIHRyYWlsZXI%3D “ 
},
{ 
title: "Akira", 
genre: "Animação", 
        ageRating: 14, 
synopsis: "Uma grande explosão fez com que Tóquio fosse destruída em 1988. Em seu lugar foi construída Neo Tóquio, que, em 2019, sofre com atentados terroristas por toda a cidade. Kaneda (Mitsuo Iwata) e Tetsuo (Nozomu Sasaki) são amigos que integram uma gangue de motoqueiros. Eles disputam rachas violentos com uma gangue rival, os Palhaços, até que um dia Tetsuo encontra Takashi (Tatsuhiko Nakamura), uma estranha criança com poderes que fugiu do hospital onde era mantido como cobaia. Tetsuo é ferido no encontro e antes de receber a ajuda dos amigos é levado por integrantes do exército, liderados pelo coronel Shikishima (Tarô Ishida). A partir de então Tetsuo passa a desenvolver poderes inimagináveis, o que faz com que seja comparado ao lendário Akira, responsável pela explosão de 1988. Paralelamente, Kaneda se interessa por Kei (Mami Koyama), uma garota envolvida com espiões que tenta decifrar o enigma por trás das cobaias controladas pelo exército.", 
trailer: "https://m.youtube.com/watch?v=0zKXoazRf-Y&pp=ygUNYWtpcmEgdHJhaWxlcg%3D%3D “
}, 
{ 
title: "Bob cuspe, nós não gostamos de gente", 
genre: "Animação", 
        ageRating: 16, 
synopsis: "Em Bob Cuspe, Nós Não Gostamos de Gente, o icônico personagem dos quadrinhos nos anos 80, Bob Cuspe, vive num deserto pós-apocalíptico infestado por astros do pop que estão sempre tentando lhe matar. O cenário onde a história se passa, na verdade, é um purgatório criado dentro da mente do criador de Bob, o cartunista Angeli.", 
trailer: "https://m.youtube.com/watch?v=ba5aViMV_8s " 
}, 
{ 
title: "Wall - e", 
genre: "Ficção Científica", 
        ageRating: Livre, 
synopsis: "Após entulhar a Terra de lixo e poluir a atmosfera com gases tóxicos, a humanidade deixou o planeta e passou a viver em uma gigantesca nave. O plano era que o retiro durasse alguns poucos anos, com robôs sendo deixados para limpar o planeta. Wall-E é o último destes robôs, que se mantém em funcionamento graças ao auto-conserto de suas peças. Sua vida consiste em compactar o lixo existente no planeta, que forma torres maiores que arranha-céus, e colecionar objetos curiosos que encontra ao realizar seu trabalho. Até que um dia surge repentinamente uma nave, que traz um novo e moderno robô: Eva. A princípio curioso, Wall-E logo se apaixona pela recém-chegada.", 
trailer: "https://m.youtube.com/watch?v=m5_lIuBXKWk&pp=ygUOd2FsbC1lIHRyYWlsZXI%3D " 
}, 
{ 
title: "Interestelar", 
genre: "Ficção Científica", 
        ageRating: 10, 
synopsis: "Após ver a Terra consumindo boa parte de suas reservas naturais, um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper (Matthew McConaughey) é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand (Anne Hathaway), Jenkins (Marlon Sanders) e Doyle (Wes Bentley), ele seguirá em busca de uma nova casa. Com o passar dos anos, sua filha Murph (Mackenzie Foy e Jessica Chastain) investirá numa própria jornada para também tentar salvar a população do planeta.", 
trailer: "https://m.youtube.com/watch?v=i6avfCqKcQo " 
},
{ 
title: "De volta para o futuro", 
genre: "Ficção Científica", 
        ageRating: 12, 
synopsis: "Após ver a Terra consumindo boa parte de suas reservas naturais, um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper (Matthew McConaughey) é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand (Anne Hathaway), Jenkins (Marlon Sanders) e Doyle (Wes Bentley), ele seguirá em busca de uma nova casa. Com o passar dos anos, sua filha Murph (Mackenzie Foy e Jessica Chastain) investirá numa própria jornada para também tentar salvar a população do planeta.", 
trailer: "https://m.youtube.com/watch?v=u0FHRJmo-xA " 
},
   { 
        title: "A origem", 
        genre: "Ficção Científica", 
        ageRating: 14, 
        synopsis: "Em um mundo onde é possível entrar na mente
        humana, Cobb (Leonardo DiCaprio) está entre os melhores na 
       arte de roubar segredos valiosos do inconsciente, durante o 
       estado de sono. Além disto ele é um fugitivo, pois está impedido
       de retornar aos Estados Unidos devido à morte de Mal (Marion 
       Cotillard). Desesperado para rever seus filhos, Cobb aceita a  
       ousada missão proposta por Saito (Ken Watanabe), um 
       empresário japonês: entrar na mente de Richard Fischer (Cillian 
       Murphy), o herdeiro de um império econômico, e plantar a ideia
       de desmembrá-lo. Para realizar este feito ele conta com a ajuda 
       do parceiro Arthur (Joseph Gordon-Levitt), a inexperiente 
       arquiteta de sonhos Ariadne (Ellen Page) e Eames (Tom 
       Hardy), que consegue se disfarçar de forma.precisa no mundo 
       dos sonhos.", 
       trailer: "https://m.youtube.com/watch?v=R_VX0e0PX90 " 
    }, 
    { 
        title: "Mad max 2_ A caçada Continua", 
        genre: "Ficção Científica", 
        ageRating: 16, 
        synopsis: "No futuro o bem mais precioso é a gasolina, em 
        virtude de uma guerra que acabou com os campos petrolíferos
        do Oriente Médio. Tendo combustível pode-se fugir da morte ou 
        se dirigir a algum lugar para matar alguém. Neste contexto, 
        Max (Mel Gibson) resolve ajudar uma comunidade a defender 
        sua refinaria contra uma gangue de motoqueiros",        trailer:"https://m.youtube.com/watch?v=EaoUt_13JJc&pp=ygUkbWFkIG1heCAyIGEgY2HDp2FkYSBjb250aW51YSB0cmFpbGVy “
    }, 
    { 
        title: "Os caçadores da arca perdida",
        genre: "Aventura", 
        ageRating: Livre, 
        synopsis: "Em 1936, o arqueólogo Indiana Jones (Harrison 
        Ford) é contratado para encontrar a Arca da Aliança, que 
        segundo as escrituras bíblicas conteria "Os Dez Mandamentos" 
        que Deus revelou a Moisés no Monte Horeb. Mas como a lenda 
        diz que o exército que a possuir será invencível, Indiana Jones 
        terá um adversário de peso na busca pela arca perdida: o 
        próprio Adolf Hitler.”,             trailer:"https://m.youtube.com/watch?v=G_wcEapEkpM&pp=ygUlb3MgY2HDp2Fkb3JlcyBkYSBhcmNhIHBlcmRpZGEgdHJhaWxlcg%3D%3D “ 
    }, 
    { 
        title: "Jumánji",
        genre: "Aventura”,
        ageRating: 10,
        synopsis: "Em 1869, dois garotos apavorados enterram um baú
        e, cem anos depois, o filho de um empresário descobre que 
        dentro dele há um jogo chamado Jumanji. Quando começa a 
        jogar com uma amiga, ele logo é penalizado a ficar na floresta 
        até que alguém tire cinco ou oito. Como na jogada seguinte ela 
        é atacada por morcegos, em virtude de seu posicionamento no 
        tabuleiro, o jogo é interrompido e ele imediatamente fica preso 
        dentro de Jumanji. Mas, vinte e seis anos depois, duas crianças 
        começam a jogar e uma acaba libertando-o. Porém, a única 
        forma de deixar tudo como antes é terminar a partida, mas para 
        isto é preciso achar a participante da partida de 1969. Juntos 
        eles enfrentam perigos, que surgem a cada jogada, e enquanto 
        o jogo se desenrola a cidade se transforma em um caos, pois 
       animais selvagens, plantas assassinas e até um caçador de 
       pessoas saem do tabuleiro e vão permanecer enquanto o jogo 
       não findar.", 
        trailer: "https://m.youtube.com/watch?v=veszTagaXik " 
    }, 
   { 
       title: "Piratas do caribe:A vingança de salazer", 
       genre: "Aventura", 
       ageRating: 12, 
       synopsis: "Em Piratas do Caribe: A Vingança de Salazar, o 
      capitão Jack Sparrow (Johnny Depp) terá que lidar com o novo 
       capitão Salazar (Javier Bardem) que lidera um exército de 
      piratas fantasmas assassinos. Salazar está disposto a matar 
       todos os piratas existentes na face da Terra e, para escapar, 
      Sparrow precisa encontrar o Tridente de Poseidon, que dá ao
       seu dono o poder de controlar o mar.”,
       trailer: "https://m.youtube.com/watch?v=fpPv8XdjW8w " 
     }, 
    { 
       title: Divergente"", 
       genre: "Aventura “,
       ageRating: 14,
       synopsis: "Divergente acompanha a adolescente Beatrice 
       (Shailene Woodley) na futurística Chicago. Ao completar 16 
       anos, a jovem terá que escolher entre as diferentes facções em 
       que a cidade está dividida. Elas são cinco e cada uma 
       representa um valor diferente, como honestidade, generosidade 
       e coragem. Beatrice surpreende a todos e até a si mesma 
       quando decide pela facção dos destemidos, diferente da família.
       Ao entrar para a Audácia ela torna-se Tris e entra numa jornada 
       para afastar seus medos e descobrir quem é de verdade. Além 
      disso conhece Quatro (Theo James), rapaz experiente que 
      consegue intrigá-la e encantá-la ao mesmo tempo.", 
       trailer:       "https://m.youtube.com/watch?v=ALIaNcHNcUs&pp=ygUSZGl2ZXJnZW50ZSB0cmFpbGVy “
    }, 
  { 
      title: "Mad max:Estradada fúria", 
      genre: "Aventura", 
      ageRating: 16,
      synopsis: "Após ser capturado por Immortan Joe, um guerreiro das estradas chamado Max (Tom Hardy) se vê no meio de uma guerra mortal, iniciada pela Imperatriz Furiosa (Charlize Theron) na tentativa se salvar um grupo de garotas. Também tentanto fugir, Max aceita ajudar Furiosa em sua luta contra Joe e se vê dividido entre mais uma vez seguir sozinho seu caminho ou ficar com o grupo.", 
     trailer: "https://m.youtube.com/watch?v=MonFNCgK4WE “
    }, ]

